language: python
python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install coveralls  

script: 
    - py.test 
    - coverage run --source candix_api -m py.test -q

after_success:
    coveralls
